name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, screenshots, etc.)
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.11.5]
        - Consoul version: [e.g., 0.2.0] (run `consoul --version`)
        - Installation method: [pip, pipx, source]
      value: |
        - OS:
        - Python version:
        - Consoul version:
        - Installation method:
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - TUI (Terminal User Interface)
        - CLI (Command Line Interface)
        - SDK/API
        - AI Provider (OpenAI, Anthropic, Google, etc.)
        - Tool Calling (file editing, code search, etc.)
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (if applicable)
      placeholder: |
        Please paste any relevant log output here.
        You can run with verbose logging: consoul --verbose
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or information here

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided all requested information
          required: true
